### ISSUE TITLE
Changelog and Roadmap

### ISSUE THREAD

**Issue by jimblue** [ApoorvSaxena/lozad.js#102]
Hi @ApoorvSaxena,

Thanks for the new release of lozad!
I was wondering how this new release is better or if there are some breaking change but it didn't found any **changelog**.

It could be nice to be able to know if it's okay to update or for debugging after an update.

Also I was wondering if you have a **roadmap** in mind for lozad?

For exemple do you plan to fix #49 ? It's a pretty old issue with multiple PR trials and discussions but it's still not fixed.

Thank for you inputs!

Cheers

**Comment by ApoorvSaxena** [comment]
@jimblue I've added a [new issue](https://github.com/ApoorvSaxena/lozad.js/issues/103) with respect to changelog. Regarding the roadmap for Lozad, functionality wise it looks complete with a few exceptions as mentioned in issues, but apart from this test coverage needs to be improved drastically, I'll list down all the points and update the README/Wiki to have everyone on the same page.

Will be reviewing https://github.com/ApoorvSaxena/lozad.js/pull/79 , had thought that the issue was resolved as per your last comment there, will be re-opening the same, please share if you have any suggestions.

**Comment by jimblue** [comment]
Hey @ApoorvSaxena, thanks for the changelog issue and the transparency about the roadmap 👍 !

About #79, you should read comments on this PR #86, me and others made some suggestions that could help you.

Cheers

**Comment by jimblue** [comment]
NICE open source project!
A changelog, what's the point, so simplier to close an issue! 🎉
