### ISSUE TITLE
Could I do before & after background images?

### ISSUE THREAD

**Issue by weilinzung** [ApoorvSaxena/lozad.js#149]
Hi, if I have an image as background and also in the pseudo setup, how I can use this lozad? or I can't?
Thanks!

Example:
```
<div class="header">Title</div>

.header::before {
    content: "";
    position: absolute;
    width: 100%;
    height: 100%;
    top: 0;
    left: 0;
    right: 0;
    z-index: -1;
    background: url(/img/assets/pattern.jpg) no-repeat center;
    background-size: cover;
}
```

**Comment by Levdbas** [comment]
Nope, this isn't possible, also due to restrictions in css pseudo elements. See https://stackoverflow.com/questions/14141374/using-css-before-and-after-pseudo-elements-with-inline-css/20288572 for a similar question.

But can't you make a child element within .header positioned absolute and use `class="lozad" data-background-image="image.png"` on that? That would be a perfect workaround in my opinion.

**Comment by weilinzung** [comment]
@Levdbas could be, but I have colour overlay of the image and then I don't have to use PhotoShop to add the overlay on the image for every time . So that is why I ask.
